// `pack-readme`: the generated pack README, runnable as a CLI and importable as `renderReadme`. From a pack's
// validated `pack.json` it emits a complete README.md — a rights-holder-agnostic non-affiliation disclaimer, a
// tagline derived from the pack fields, the themed statusline shot, the single figure (verbatim glyphs, no
// ANSI), a one-line-per-pool voice sample, and attribution. The CLI reads `<dir>/pack.json`, narrows it through
// the schema guard, and writes `<dir>/README.md`. The statusline image it references is produced separately by
// `scripts/assets/pack-shot.sh`. Consumed by the pack-author skill and the ship review.
//
// renderReadme consumes the already-validated, fully typed `PackJson`, so it never touches loose JSON (no
// `no-unsafe-*` carve-out here); only the CLI's `JSON.parse` boundary handles `unknown`.

import { readFileSync, realpathSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import type { PackJson } from "../domain";

import { validatePackDetailed } from "./validate";

type Record1 = Readonly<Record<string, readonly string[]>>;
type Record2 = Readonly<Record<string, Record1>>;

const firstOf1 = (r: Record1): string | undefined => {
	for (const arr of Object.values(r)) if (arr[0] !== undefined) return arr[0];
	return undefined;
};

const firstOf2 = (r: Record2): string | undefined => {
	for (const inner of Object.values(r)) {
		const line = firstOf1(inner);
		if (line !== undefined) return line;
	}
	return undefined;
};

interface PoolLine {
	readonly label: string;
	readonly line: string | undefined;
}

// One representative line per pool, in pack.json declaration order.
function voiceCatalog(p: PackJson): PoolLine[] {
	const l = p.lines;
	return [
		{ label: "mood", line: firstOf2(l.mood) },
		{ label: "greeting", line: firstOf2(l.greeting) },
		{ label: "firstContact", line: firstOf1(l.firstContact) },
		{ label: "milestone", line: firstOf2(l.milestone) },
		{ label: "positiveGit", line: firstOf2(l.positiveGit) },
		{ label: "egg", line: firstOf1(l.egg) },
		{ label: "event", line: firstOf1(l.event) },
		{ label: "stack", line: firstOf2(l.stack) },
		{ label: "pressure", line: firstOf1(l.pressure) },
		{ label: "dateEgg", line: l.dateEgg[0] },
	];
}

// The pack's single figure, verbatim glyphs in a fenced block. No ANSI, no blank normalization: U+2800 stays so
// braille figures keep their uniform-width padding (converting it to a space misaligns some fonts). The colored,
// theme-painted look lives in the statusline shot above, not here.
function figureSection(p: PackJson): string {
	return `\`\`\`\n${p.art.join("\n")}\n\`\`\``;
}

// Generic and rights-holder-agnostic so it scales to any character.
const DISCLAIMER =
	"> Fan-made tribute. Character names and likenesses are trademarks of their respective owners; this " +
	"pack is an unofficial, non-commercial homage, not affiliated with or endorsed by them.";

export function renderReadme(pack: PackJson): string {
	const out: string[] = [
		`# ${pack.displayName} pack`,
		"",
		DISCLAIMER,
		"",
		`${pack.emblem} **${pack.displayName}** — a reactive ccsidekick character, _${pack.tone}_ in tone.`,
		"",
		"## Statusline",
		"",
		`![${pack.displayName} statusline](./assets/statusline.svg)`,
		"",
		"## Figure",
		"",
		figureSection(pack),
		"",
		"## Voice",
		"",
		"One representative line per pool:",
		"",
	];
	for (const { label, line } of voiceCatalog(pack))
		out.push(`- **${label}**: ${line ?? "(none authored)"}`);
	out.push(`- **spinnerVerbs**: ${pack.spinnerVerbs.join(", ")}`, "");
	out.push("## Attribution", "");
	out.push(`- tone: ${pack.tone}`);
	out.push(`- emblem: ${pack.emblem}`);
	out.push(`- artist: ${pack.attribution.artist}`);
	out.push(`- source: ${pack.attribution.source}`);
	out.push("", "<!-- generated by `bun run pack-readme <dir>`; do not edit -->", "");
	return out.join("\n");
}

function runCli(): void {
	const dir = process.argv.slice(2).find((a) => !a.startsWith("--"));
	if (dir === undefined) {
		process.stderr.write("usage: pack-readme <pack-dir>\n");
		process.exit(2);
	}
	let raw: unknown;
	try {
		raw = JSON.parse(readFileSync(join(dir, "pack.json"), "utf8")) as unknown;
	} catch (e) {
		const msg = e instanceof Error ? e.message : String(e);
		process.stderr.write(`pack-readme: failed to read ${dir}/pack.json: ${msg}\n`);
		process.exit(2);
	}
	const result = validatePackDetailed(raw);
	if ("error" in result) {
		process.stderr.write(`pack-readme: ${result.error}\n`);
		process.exit(1);
	}
	const outPath = join(dir, "README.md");
	writeFileSync(outPath, renderReadme(result.pack), "utf8");
	process.stdout.write(`pack-readme: wrote ${outPath}\n`);
	process.exit(0);
}

const invoked = process.argv[1];
if (invoked !== undefined && realpathSync(invoked) === fileURLToPath(import.meta.url)) runCli();
