import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, expect, test } from "bun:test";

import fixture from "../../test/fixtures/packs/valid/pack.json";
import { stripAnsi } from "../render";

import { renderReadme } from "./readme";
import { validatePack } from "./validate";

const tmpDirs: string[] = [];
afterEach(() => {
	for (const d of tmpDirs) rmSync(d, { recursive: true, force: true });
	tmpDirs.length = 0;
});
function track(d: string): string {
	tmpDirs.push(d);
	return d;
}

const pack = validatePack(fixture);
if (pack === null) throw new Error("fixture pack failed validation");

const fixtureJson = join(import.meta.dir, "../../test/fixtures/packs/valid/pack.json");
const readmeTs = join(import.meta.dir, "readme.ts");

test("emits the README skeleton: heading, disclaimer, tagline, and the section headers", () => {
	const md = renderReadme(pack);
	expect(md).toContain("# Fixture pack");
	expect(md).toContain("not affiliated with or endorsed by them"); // generic non-affiliation disclaimer
	expect(md).toContain("**Fixture** — a reactive ccsidekick character, _mild_ in tone."); // tagline
	expect(md).toContain("## Statusline");
	expect(md).toContain("## Figure");
	expect(md).toContain("## Voice");
	expect(md).toContain("## Attribution");
	expect(md).toContain("<!-- generated by `bun run pack-readme <dir>`; do not edit -->");
});

test("links the themed statusline shot in the pack's own assets", () => {
	const md = renderReadme(pack);
	expect(md).toContain("![Fixture statusline](./assets/statusline.svg)");
});

test("renders the single figure once", () => {
	const md = renderReadme(pack);
	expect(md).toContain("## Figure");
	expect(md).not.toContain("### idle"); // no per-mood headers; the figure is a single static array
	expect(md.split("```").length - 1).toBe(2); // exactly one fenced figure block
	expect(stripAnsi(md)).toContain("FIXTURE"); // glyphs survive verbatim
});

test("includes a representative line from each authored voice pool", () => {
	const md = renderReadme(pack);
	expect(md).toContain("mood idle stranger line");
	expect(md).toContain("greeting morning stranger line");
	expect(md).toContain("first contact stranger line");
	expect(md).toContain("milestone tier_up stranger line");
	expect(md).toContain("git clean_tree stranger line");
	expect(md).toContain("egg stranger line");
	expect(md).toContain("event test_fail reaction");
	expect(md).toContain("web slow");
	expect(md).toContain("pressure compact_hint");
	expect(md).toContain("a special-day easter egg");
	expect(md).toContain("pondering"); // a spinner verb
});

test("the figure section is verbatim glyphs: no ANSI, braille blanks preserved", () => {
	const batman = validatePack(
		JSON.parse(readFileSync(join(import.meta.dir, "../../../packs/batman/pack.json"), "utf8")),
	);
	if (batman === null) throw new Error("batman pack failed validation");
	const md = renderReadme(batman);
	expect(md).not.toContain("\x1b["); // no ESC codes anywhere
	for (const row of batman.art) expect(md).toContain(row); // every art row verbatim (U+2800 preserved)
});

test("CLI writes README.md next to the pack.json", () => {
	const dir = track(mkdtempSync(join(tmpdir(), "ccsidekick-readme-")));
	copyFileSync(fixtureJson, join(dir, "pack.json"));
	const run = spawnSync("bun", [readmeTs, dir], { encoding: "utf8" });
	expect(run.status).toBe(0);
	const outPath = join(dir, "README.md");
	expect(existsSync(outPath)).toBe(true);
	expect(readFileSync(outPath, "utf8")).toContain("mood idle stranger line");
});
